SETTINGS:
  isPrivateServer: false
  spawnOnJoin: false
  spawnOnDie: true
  spawnOverrideBedSpawn: false
  spawnIfNoBed: true
  serverName: A minecraft server
  showDeathCoordinates: true
  serverLanguage: en_us
  perWarpPermission: false
  #You can use #sender# placeholder to see the sender's name (nothing if from console).
  broadcastPrefix: "ยง7[ยง4#server_name#ยง7]ยงf: "
SPAWN:
  world:
  x:
  y:
  z:
  pitch:
  yaw:
WARPS: {}