SETTINGS:
  isPrivateServer: false
  spawnOnJoin: false
  spawnOnDie: true
  spawnOverrideBedSpawn: false
  spawnIfNoBed: true
  serverName: A minecraft server
  showDeathCoordinates: true
  serverLanguage: en_us
  perWarpPermission: false
  #You can use #sender# placeholder to see the sender's name (nothing if from console).
  broadcastPrefix: "ยง7[ยง4#server_name#ยง7]ยงf: "
  website: ""
  discord: ""
  change_all_worlds_time: true
  change_all_worlds_weather: true
  new_weather_duration: 10000
  default_homes_limit: 1
  default_delays:
    home: 2
    tpa: 2
    tpahere: 2
    back: 2
    warp: 2
    spawn: 0
  per_warp_delay: false
SPAWN:
  world:
  x:
  y:
  z:
  pitch:
  yaw:
WARPS: {}