name: MysticEssentials
author: Choco70
main: fr.choco70.mysticessentials.MysticEssentials
version: 1.4.0
api-version: 1.14
softdepend: [Vault]
commands:
  spawn:
    description: Teleport to spawn.
    permission: mysticessentials.spawn
    permission-message: You don't have permission to teleport to spawn. (mysticessentials.spawn)
  setspawn:
    description: Make your position the server's spawn.
    permission: mysticessentials.setspawn
    permission-message: You don't have permission to set the spawn.
  delspawn:
    description: Remove the spawn location.
    permission: mysticessentials.delspawn
    permission-message: You don't have permission to remove the spawn.
  home:
    description: Teleport to home <home>.
    permission: mysticessentials.home
    permission-message: You don't have permission to use home (mysticessentials.home)
    usage: "Correct usage: /home <home_name>"
  sethome:
    description: Setup home <home>.
    permission: mysticessentials.sethome
    permission-message: You don't have permission to set a home (mysticessentials.sethome)
    usage: "Correct usage: /sethome <home_name>"
  delhome:
    description: Remove home <home>.
    permission: mysticessentials.delhome
    permission-message: You don't have permission to useset a home (mysticessentials.delhome)
    usage: "Correct usage: /delhome <home_name>"
  tpa:
    description: Send a request to teleport to another player.
    permission: mysticessentials.tpa
    permission-message: You don't have permission to use tpa (mysticessentials.tpa)
  tpahere:
    description: Send a request to teleport a player to you.
    permission: mysticessentials.tpahere
    permission-message: You don't have permission to use tpahere (mysticessentials.tpahere)
  tpaccept:
    description: Accept teleport request from a player.
    permission: mysticessentials.tpaccept
    permission-message: You don't have permission to use tpaccept (mysticessentials.tpaccept)
  tpdeny:
    description: Deny teleport request from a player.
    permission: mysticessentials.tpdeny
    permission-message: You don't have permission to use tpdeny (mysticessentials.tpdeny)
  back:
    description: Teleport to your last death location.
    permission: mysticessentials.back
    permission-message: You don't have permission to use the back command (mysticessentials.back)
  setlanguage:
    description: Change your language.
    permission: mysticessentials.setlanguage
    permission-message: You don't have permission to change your language. (mysticessentials.setlanguage)
    usage: "Correct usage: /setlanguage <language ex: en_us>"
    aliases: [langset, lang, setlang]
  homelist:
    description: View your homes list.
    permission: mysticessentials.homelist
    permission-message: You don't have permission to use /homelist command. (mysticessentials.homelist)
    usage: "Correct usage: /homelist"
    aliases: [homes]
  warp:
    description: Teleport you to a warp.
    permission: mysticessentials.warp
    permission-message: You don't have permission to teleport you to a warp.
    usage: "Correct usage: /warp <warp_name or list>"
  setwarp:
    description: Add a new warp.
    permission: mysticessentials.setwarp
    permission-message: You don't have permission to add a new warp.
    usage: "Correct usage: /setwarp <warp_name>"
  delwarp:
    description: Remove a warp.
    permission: mysticessentials.delwarp
    permission-message: You don't have permission to remove a warp.
    usage: "Correct usage: /delwarp <warp_name>"
  warplist:
    description: List all warps.
    permission: mysticessentials.warplist
    permission-message: You don't have permission to list warps.
    usage: "Correct usage: /warplist"
    aliases: [warps]
  feed:
    description: Feed you or a player.
    permission: mysticessentials.feed
    permission-message: You don't have permission to use feed command.
    usage: "Correct usage: /feed [player]"
  fly:
    description: Allows to fly.
    permission: mysticessentials.fly
    permission-message: You don't have permission to use fly command.
    usage: "Correct usage: /fly [player]"
  msg:
    description: Used to send private messages.
    permission: mysticessentials.msg
    permission-message: You don't have permission to use msg command.
    usage: "Correct usage: /msg <player> <message>"
    aliases: [message, w]
  reply:
    description: Used to reply to a private message.
    permission: mysticessentials.reply
    permission-message: You don't have permission to use reply command.
    usage: "Correct usage: /reply [player] <message>"
    aliases: [r]
  ignore:
    description: Ignore private messages from a player.
    permission: mysticessentials.ignore
    permission-message: You don't have permission to use ignore command.
    usage: "Correct usage: /ignore <player or list>"
  ignorelist:
    description: View the list of players you ignore.
    permission: mysticessentials.ignorelist
    permission-message: You don't have permission to use ignorelist command.
    usage: "Correct usage: /ignorelist"
  broadcast:
    description: Send an anonymous message to the whole server.
    permission: mysticessentials.broadcast
    permission-message: You don't have permission to use broadcast command.
    usage: "Correct usage: /broadcast <message>"
    aliases: [bc, bcast]
  rules:
    description: See the server's rules.
    permission: mysticessentials.rules
    permission-message: You don't have permission to use rules command.
    usage: "Correct usage: /rules [number]"
  sun:
    description: Set weather to sun.
    permission: mysticessentials.weather.sun
    permission-message: You don't have permission to use sun command.
    usage: "Correct usage: /sun"
  rain:
    description: Set weather to rain.
    permission: mysticessentials.weather.rain
    permission-message: You don't have permission to use rain command.
    usage: "Correct usage: /rain"
  storm:
    description: Set weather to storm.
    permission: mysticessentials.weather.storm
    permission-message: You don't have permission to use storm command.
    usage: "Correct usage: /storm"
  day:
    description: Set time to day.
    permission: mysticessentials.time.day
    permission-message: You don't have permission to use day command.
    usage: "Correct usage: /day"
  night:
    description: Set time to night.
    permission: mysticessentials.time.night
    permission-message: You don't have permission to use night command.
    usage: "Correct usage: /night"
  balance:
    description: See your money or money from an other player.
    permission: mysticessentials.balance
    permission-message: You don't have permission to use balance command.
    usage: "Correct usage: /balance [player] - Needs Vault with a valid economy plugin."
    aliases: [bal, money]
  setdefaulthome:
    description: Set your default home.
    permission: mysticessentials.setdefaulthome
    permission-message: You don't have permission to define your default home.
    usage: "Correct usage: /setdefaulthome <home>"
#  mysticessentialsreload:
#    aliases: [mereload, mysticereload, messentialsreload, mer, mysticer, messentialsr]
#    description: Reload plugin's configuration.
#    permission: mysticessentials.reload
#    permission-message: You don't have permission to use the reload command (mysticessentials.reload)
permissions:
  mysticessentials.spawn:
    default: true
    description: Allows to use /spawn command.
  mysticessentials.setspawn:
    default: op
    description: Allows to set the spawn.
  mysticessentials.delspawn:
    default: op
    description: Allows to remove the spawn.
  mysticessentials.home:
    default: true
    description: Allows to use /home command.
  mysticessentials.delhome:
    default: true
    description: Allows to use /delhome command.
  mysticessentials.sethome:
    default: true
    description: Allows to use /sethome command.
  mysticessentials.tpa:
    default: true
    description: Allows to use /tpa command.
  mysticessentials.tpahere:
    default: true
    description: Allows to use /tpahere command.
  mysticessentials.tpaccept:
    default: true
    description: Allows to use /tpaccept command.
  mysticessentials.tpdeny:
    default: true
    description: Allows to use /tpdeny command.
  mysticessentials.back:
    default: op
    description: Allows to use /back command.
  mysticessentials.setlanguage:
    default: true
    description: Allows to use /setlanguage command.
  mysticessentials.homelist:
    default: true
    description: Allows to use /homelist command.
  mysticessentials.warp:
    default: true
    description: Allows to use /warp command.
  mysticessentials.setwarp:
    default: op
    description: Allows to use /setwarp command.
  mysticessentials.delwarp:
    default: op
    description: Allows to use /delwarp command.
  mysticessentials.warplist:
    default: true
    description: Allows to use /warplist command.
  mysticessentials.feed:
    default: op
    description: Allows to use /feed command.
  mysticessentials.feed.others:
    default: op
    description: Allows to use /feed command on another player.
    children:
      mysticessentials.feed: true
  mysticessentials.fly:
    default: op
    description: Allows to use /fly command.
  mysticessentials.fly.others:
    default: op
    description: Allows to use /fly command on another player.
    children:
      mysticessentials.fly: true
  mysticessentials.msg:
    default: true
    description: Allows to use /msg command.
  mysticessentials.reply:
    default: true
    description: Allows to use /reply command.
  mysticessentials.ignore:
    default: true
    description: Allows to use /ignore command.
  mysticessentials.ignore.bypass:
    default: op
    description: Allow a player to don't be ignored.
  mysticessentials.ignorelist:
    default: true
    description: Allows to use /ignorelist command.
  mysticessentials.broadcast:
    default: op
    description: Allows to use /broadcast command.
  mysticessentials.homeslimit.nolimit:
    default: op
    description: Allows to set an unlimited homes number.
  mysticessentials.homeslimit:
    default: false
    description: Allows to set a limit of homes set.
  mysticessentials.balance:
    default: true
    description: Allows to use /balance command.
  mysticessentials.balance.others:
    default: true
    description: Allows to use /balance [player] command.
    children:
      mysticessentials.balance: true
  mysticessentials.rules:
    default: true
    description: Allows to use /rules command.
  mysticessentials.weather.sun:
    default: op
    description: Allows to use /sun command.
  mysticessentials.weather.rain:
    default: op
    description: Allows to use /rain command.
  mysticessentials.weather.storm:
    default: op
    description: Allows to use /storm command.
  mysticessentials.weather.*:
    default: op
    description: Allows to use weather commands.
    children:
      mysticessentials.weather.sun: true
      mysticessentials.weather.rain: true
      mysticessentials.weather.storm: true
  mysticessentials.time.day:
    default: op
    description: Allows to use /day command.
  mysticessentials.time.night:
    default: op
    description: Allows to use /night command.
  mysticessentials.time.*:
    default: op
    description: Allows to use time commands.
    children:
      mysticessentials.time.day: true
      mysticessentials.time.night: true
  mysticessentials.setdefaulthome:
    default: true
    description: Allows to use /setdefaulthome command.
#  mysticessentials.reload:
#    default: op
#    description: Allows to use /mysticessentialsreload command